using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

[Preserve]
public sealed partial class DB_Fish : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5560984306225763593UL,9892102557027751583UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.Int32 FishId
	{
		get => _FishId[Index];
		set => _FishId.SetValue(this, value);
	}
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String Description
	{
		get => _Description[Index];
		set => _Description[Index] = value;
	}
	public System.String Position
	{
		get => _Position[Index];
		set => _Position[Index] = value;
	}
	public System.String Skill_name
	{
		get => _Skill_name[Index];
		set => _Skill_name[Index] = value;
	}
	public System.Int32 Damage
	{
		get => _Damage[Index];
		set => _Damage.SetValue(this, value);
	}
	public System.Int32 Heal
	{
		get => _Heal[Index];
		set => _Heal.SetValue(this, value);
	}
	public System.Int32 Hp
	{
		get => _Hp[Index];
		set => _Hp.SetValue(this, value);
	}
	public System.Int32 AbilityToAct
	{
		get => _AbilityToAct[Index];
		set => _AbilityToAct.SetValue(this, value);
	}
	public System.String Habitat
	{
		get => _Habitat[Index];
		set => _Habitat[Index] = value;
	}
	public System.Int32 Probability
	{
		get => _Probability[Index];
		set => _Probability.SetValue(this, value);
	}
	public System.Int32 MaxStackSize
	{
		get => _MaxStackSize[Index];
		set => _MaxStackSize.SetValue(this, value);
	}
	public System.Boolean IsPlayerCard
	{
		get => _IsPlayerCard[Index];
		set => _IsPlayerCard.SetValue(this, value);
	}
	public System.String Prefab
	{
		get => _Prefab[Index];
		set => _Prefab[Index] = value;
	}
	public System.String AbilityToAct_icon
	{
		get => _AbilityToAct_icon[Index];
		set => _AbilityToAct_icon[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_FishId;
	public static BansheeGz.BGDatabase.BGFieldInt _FishId => _ufle12jhs77_FishId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5738085357535783960UL, 12879849390299136128UL), () => _ufle12jhs77_FishId = null);
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5045520561611985804UL, 12371104935179130035UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Description;
	public static BansheeGz.BGDatabase.BGFieldString _Description => _ufle12jhs77_Description ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4951050286627185142UL, 1447691313761944220UL), () => _ufle12jhs77_Description = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Position;
	public static BansheeGz.BGDatabase.BGFieldString _Position => _ufle12jhs77_Position ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5458218424951999417UL, 7124783479407722687UL), () => _ufle12jhs77_Position = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Skill_name;
	public static BansheeGz.BGDatabase.BGFieldString _Skill_name => _ufle12jhs77_Skill_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4687308779892288187UL, 11404193653849018288UL), () => _ufle12jhs77_Skill_name = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Damage;
	public static BansheeGz.BGDatabase.BGFieldInt _Damage => _ufle12jhs77_Damage ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5751248046732169612UL, 2868805763113974935UL), () => _ufle12jhs77_Damage = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Heal;
	public static BansheeGz.BGDatabase.BGFieldInt _Heal => _ufle12jhs77_Heal ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5454052037782380401UL, 14008414421192123017UL), () => _ufle12jhs77_Heal = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Hp;
	public static BansheeGz.BGDatabase.BGFieldInt _Hp => _ufle12jhs77_Hp ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5704705637946529922UL, 7991778845071206046UL), () => _ufle12jhs77_Hp = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_AbilityToAct;
	public static BansheeGz.BGDatabase.BGFieldInt _AbilityToAct => _ufle12jhs77_AbilityToAct ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5368075965366420038UL, 3628174215926008226UL), () => _ufle12jhs77_AbilityToAct = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Habitat;
	public static BansheeGz.BGDatabase.BGFieldString _Habitat => _ufle12jhs77_Habitat ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4878435364413157747UL, 640765528284393649UL), () => _ufle12jhs77_Habitat = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Probability;
	public static BansheeGz.BGDatabase.BGFieldInt _Probability => _ufle12jhs77_Probability ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5261378452605459351UL, 14491805233951288455UL), () => _ufle12jhs77_Probability = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_MaxStackSize;
	public static BansheeGz.BGDatabase.BGFieldInt _MaxStackSize => _ufle12jhs77_MaxStackSize ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5211317728524813621UL, 2693696612521573005UL), () => _ufle12jhs77_MaxStackSize = null);
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77_IsPlayerCard;
	public static BansheeGz.BGDatabase.BGFieldBool _IsPlayerCard => _ufle12jhs77_IsPlayerCard ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(4665905885988586443UL, 1653607090037436589UL), () => _ufle12jhs77_IsPlayerCard = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Prefab;
	public static BansheeGz.BGDatabase.BGFieldString _Prefab => _ufle12jhs77_Prefab ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4664416041449059695UL, 13939171338268991669UL), () => _ufle12jhs77_Prefab = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_AbilityToAct_icon;
	public static BansheeGz.BGDatabase.BGFieldString _AbilityToAct_icon => _ufle12jhs77_AbilityToAct_icon ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5510431125834546457UL, 13703688639673701812UL), () => _ufle12jhs77_AbilityToAct_icon = null);
	private DB_Fish() : base(MetaDefault) {}
	private DB_Fish(BGId id) : base(MetaDefault, id) {}
	private DB_Fish(BGMetaEntity meta) : base(meta) {}
	private DB_Fish(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_Fish FindEntity(Predicate<DB_Fish> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_Fish> FindEntities(Predicate<DB_Fish> filter, List<DB_Fish> result=null, Comparison<DB_Fish> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Fish> action, Predicate<DB_Fish> filter=null, Comparison<DB_Fish> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_Fish GetEntity(BGId entityId) => (DB_Fish) MetaDefault.GetEntity(entityId);
	public static DB_Fish GetEntity(int index) => (DB_Fish) MetaDefault[index];
	public static DB_Fish GetEntity(string entityName) => (DB_Fish) MetaDefault.GetEntity(entityName);
	public static DB_Fish NewEntity() => (DB_Fish) MetaDefault.NewEntity();
	public static DB_Fish NewEntity(BGId entityId) => (DB_Fish) MetaDefault.NewEntity(entityId);
	public static DB_Fish NewEntity(Action<DB_Fish> callback) => (DB_Fish) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_Fish)entity)));
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5560984306225763593UL,9892102557027751583UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_FishId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5738085357535783960UL, 12879849390299136128UL));
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5045520561611985804UL, 12371104935179130035UL));
		_ufle12jhs77_Description = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4951050286627185142UL, 1447691313761944220UL));
		_ufle12jhs77_Position = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5458218424951999417UL, 7124783479407722687UL));
		_ufle12jhs77_Skill_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4687308779892288187UL, 11404193653849018288UL));
		_ufle12jhs77_Damage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5751248046732169612UL, 2868805763113974935UL));
		_ufle12jhs77_Heal = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5454052037782380401UL, 14008414421192123017UL));
		_ufle12jhs77_Hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5704705637946529922UL, 7991778845071206046UL));
		_ufle12jhs77_AbilityToAct = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5368075965366420038UL, 3628174215926008226UL));
		_ufle12jhs77_Habitat = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4878435364413157747UL, 640765528284393649UL));
		_ufle12jhs77_Probability = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5261378452605459351UL, 14491805233951288455UL));
		_ufle12jhs77_MaxStackSize = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5211317728524813621UL, 2693696612521573005UL));
		_ufle12jhs77_IsPlayerCard = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(_metaDefault, new BGId(4665905885988586443UL, 1653607090037436589UL));
		_ufle12jhs77_Prefab = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4664416041449059695UL, 13939171338268991669UL));
		_ufle12jhs77_AbilityToAct_icon = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5510431125834546457UL, 13703688639673701812UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_FishId = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_Description = null;
		_ufle12jhs77_Position = null;
		_ufle12jhs77_Skill_name = null;
		_ufle12jhs77_Damage = null;
		_ufle12jhs77_Heal = null;
		_ufle12jhs77_Hp = null;
		_ufle12jhs77_AbilityToAct = null;
		_ufle12jhs77_Habitat = null;
		_ufle12jhs77_Probability = null;
		_ufle12jhs77_MaxStackSize = null;
		_ufle12jhs77_IsPlayerCard = null;
		_ufle12jhs77_Prefab = null;
		_ufle12jhs77_AbilityToAct_icon = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Fish(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Fish(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "Fish";
		public const string FishId = "FishId";
		public const string name = "name";
		public const string Description = "Description";
		public const string Position = "Position";
		public const string Skill_name = "Skill_name";
		public const string Damage = "Damage";
		public const string Heal = "Heal";
		public const string Hp = "Hp";
		public const string AbilityToAct = "AbilityToAct";
		public const string Habitat = "Habitat";
		public const string Probability = "Probability";
		public const string MaxStackSize = "MaxStackSize";
		public const string IsPlayerCard = "IsPlayerCard";
		public const string Prefab = "Prefab";
		public const string AbilityToAct_icon = "AbilityToAct_icon";
	}
}

[Preserve]
public sealed partial class DB_GameDialog : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5584336644477304854UL,17433534054083016846UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.Int32 DialogId
	{
		get => _DialogId[Index];
		set => _DialogId.SetValue(this, value);
	}
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.String text
	{
		get => _text[Index];
		set => _text[Index] = value;
	}
	public System.Int32 nextId
	{
		get => _nextId[Index];
		set => _nextId.SetValue(this, value);
	}
	public System.String portraitPath
	{
		get => _portraitPath[Index];
		set => _portraitPath[Index] = value;
	}
	public List<DB_Choices> choices
	{
		get => BGCodeGenUtils.MultipleRelationGet<DB_Choices>(_choices, Index);
		set => BGCodeGenUtils.MultipleRelationSet<DB_Choices>(_choices, Index, value);
	}
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_DialogId;
	public static BansheeGz.BGDatabase.BGFieldInt _DialogId => _ufle12jhs77_DialogId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5027862820673451380UL, 3078999230340777089UL), () => _ufle12jhs77_DialogId = null);
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(4992978860123395449UL, 10013648162712444847UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_text;
	public static BansheeGz.BGDatabase.BGFieldString _text => _ufle12jhs77_text ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4696875784822327232UL, 8036504191935424388UL), () => _ufle12jhs77_text = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_nextId;
	public static BansheeGz.BGDatabase.BGFieldInt _nextId => _ufle12jhs77_nextId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5072672786422525844UL, 17266666896676044206UL), () => _ufle12jhs77_nextId = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_portraitPath;
	public static BansheeGz.BGDatabase.BGFieldString _portraitPath => _ufle12jhs77_portraitPath ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4646365072518137967UL, 9448667769619321731UL), () => _ufle12jhs77_portraitPath = null);
	private static BansheeGz.BGDatabase.BGFieldRelationMultiple _ufle12jhs77_choices;
	public static BansheeGz.BGDatabase.BGFieldRelationMultiple _choices => _ufle12jhs77_choices ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(MetaDefault, new BGId(4861534693419869178UL, 6093048913292466840UL), () => _ufle12jhs77_choices = null);
	private DB_GameDialog() : base(MetaDefault) {}
	private DB_GameDialog(BGId id) : base(MetaDefault, id) {}
	private DB_GameDialog(BGMetaEntity meta) : base(meta) {}
	private DB_GameDialog(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_GameDialog FindEntity(Predicate<DB_GameDialog> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_GameDialog> FindEntities(Predicate<DB_GameDialog> filter, List<DB_GameDialog> result=null, Comparison<DB_GameDialog> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_GameDialog> action, Predicate<DB_GameDialog> filter=null, Comparison<DB_GameDialog> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_GameDialog GetEntity(BGId entityId) => (DB_GameDialog) MetaDefault.GetEntity(entityId);
	public static DB_GameDialog GetEntity(int index) => (DB_GameDialog) MetaDefault[index];
	public static DB_GameDialog GetEntity(string entityName) => (DB_GameDialog) MetaDefault.GetEntity(entityName);
	public static DB_GameDialog NewEntity() => (DB_GameDialog) MetaDefault.NewEntity();
	public static DB_GameDialog NewEntity(BGId entityId) => (DB_GameDialog) MetaDefault.NewEntity(entityId);
	public static DB_GameDialog NewEntity(Action<DB_GameDialog> callback) => (DB_GameDialog) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_GameDialog)entity)));
	public void choices_Add(DB_Choices related) => BGCodeGenUtils.MultipleRelationAdd(_choices, Index, related);
	public void choices_Remove(DB_Choices related) => BGCodeGenUtils.MultipleRelationRemove(_choices, Index, related);
	public List<DB_Choices> Fillchoices(List<DB_Choices> result) => BGCodeGenUtils.MultipleRelationGet<DB_Choices>(_choices, Index, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5584336644477304854UL,17433534054083016846UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_DialogId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5027862820673451380UL, 3078999230340777089UL));
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(4992978860123395449UL, 10013648162712444847UL));
		_ufle12jhs77_text = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4696875784822327232UL, 8036504191935424388UL));
		_ufle12jhs77_nextId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5072672786422525844UL, 17266666896676044206UL));
		_ufle12jhs77_portraitPath = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(4646365072518137967UL, 9448667769619321731UL));
		_ufle12jhs77_choices = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldRelationMultiple>(_metaDefault, new BGId(4861534693419869178UL, 6093048913292466840UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_DialogId = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_text = null;
		_ufle12jhs77_nextId = null;
		_ufle12jhs77_portraitPath = null;
		_ufle12jhs77_choices = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_GameDialog(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_GameDialog(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "GameDialog";
		public const string DialogId = "DialogId";
		public const string name = "name";
		public const string text = "text";
		public const string nextId = "nextId";
		public const string portraitPath = "portraitPath";
		public const string choices = "choices";
	}
}

[Preserve]
public sealed partial class DB_Choices : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ??= BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5417390207575500735UL,97964437334847379UL), () => _metaDefault = null);
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.Int32 ChoiceId
	{
		get => _ChoiceId[Index];
		set => _ChoiceId.SetValue(this, value);
	}
	public System.String choiceText
	{
		get => _choiceText[Index];
		set => _choiceText[Index] = value;
	}
	public System.Int32 choiceNextId
	{
		get => _choiceNextId[Index];
		set => _choiceNextId.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5547687542920768842UL, 315184727022763183UL), () => _ufle12jhs77_name = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_ChoiceId;
	public static BansheeGz.BGDatabase.BGFieldInt _ChoiceId => _ufle12jhs77_ChoiceId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5308457029506116295UL, 2374685375725347484UL), () => _ufle12jhs77_ChoiceId = null);
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_choiceText;
	public static BansheeGz.BGDatabase.BGFieldString _choiceText => _ufle12jhs77_choiceText ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5386551107550435528UL, 860956536653701041UL), () => _ufle12jhs77_choiceText = null);
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_choiceNextId;
	public static BansheeGz.BGDatabase.BGFieldInt _choiceNextId => _ufle12jhs77_choiceNextId ??= BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4764995010668862391UL, 5364007493517493931UL), () => _ufle12jhs77_choiceNextId = null);
	public List<DB_GameDialog> RelatedGameDialogListUsingchoicesRelation => BGCodeGenUtils.GetRelatedInbound<DB_GameDialog>(DB_GameDialog._choices, Id);
	private DB_Choices() : base(MetaDefault) {}
	private DB_Choices(BGId id) : base(MetaDefault, id) {}
	private DB_Choices(BGMetaEntity meta) : base(meta) {}
	private DB_Choices(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_Choices FindEntity(Predicate<DB_Choices> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_Choices> FindEntities(Predicate<DB_Choices> filter, List<DB_Choices> result=null, Comparison<DB_Choices> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_Choices> action, Predicate<DB_Choices> filter=null, Comparison<DB_Choices> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_Choices GetEntity(BGId entityId) => (DB_Choices) MetaDefault.GetEntity(entityId);
	public static DB_Choices GetEntity(int index) => (DB_Choices) MetaDefault[index];
	public static DB_Choices GetEntity(string entityName) => (DB_Choices) MetaDefault.GetEntity(entityName);
	public static DB_Choices NewEntity() => (DB_Choices) MetaDefault.NewEntity();
	public static DB_Choices NewEntity(BGId entityId) => (DB_Choices) MetaDefault.NewEntity(entityId);
	public static DB_Choices NewEntity(Action<DB_Choices> callback) => (DB_Choices) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_Choices)entity)));
	public List<DB_GameDialog> FillRelatedGameDialogListUsingchoicesRelation(List<DB_GameDialog> result) => BGCodeGenUtils.GetRelatedInbound<DB_GameDialog>(DB_GameDialog._choices, Id, result);
	public static void InitializeCodeGenRuntime()
	{
		_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5417390207575500735UL,97964437334847379UL), ReleaseCodeGenRuntime);
		_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(_metaDefault, new BGId(5547687542920768842UL, 315184727022763183UL));
		_ufle12jhs77_ChoiceId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(5308457029506116295UL, 2374685375725347484UL));
		_ufle12jhs77_choiceText = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(_metaDefault, new BGId(5386551107550435528UL, 860956536653701041UL));
		_ufle12jhs77_choiceNextId = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(_metaDefault, new BGId(4764995010668862391UL, 5364007493517493931UL));
	}
	public static void ReleaseCodeGenRuntime()
	{
		_metaDefault = null;
		_ufle12jhs77_name = null;
		_ufle12jhs77_ChoiceId = null;
		_ufle12jhs77_choiceText = null;
		_ufle12jhs77_choiceNextId = null;
	}

	[Preserve]
	public sealed class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_Choices(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_Choices(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "Choices";
		public const string name = "name";
		public const string ChoiceId = "ChoiceId";
		public const string choiceText = "choiceText";
		public const string choiceNextId = "choiceNextId";
	}
}

[Preserve]
public static class BGCodeGenRuntimeInitializer
{
	[Preserve]
	public static void InitializeCodeGenRuntime()
	{
		DB_Fish.InitializeCodeGenRuntime();
		DB_GameDialog.InitializeCodeGenRuntime();
		DB_Choices.InitializeCodeGenRuntime();
	}
	[Preserve]
	public static void ReleaseCodeGenRuntime()
	{
		DB_Fish.ReleaseCodeGenRuntime();
		DB_GameDialog.ReleaseCodeGenRuntime();
		DB_Choices.ReleaseCodeGenRuntime();
	}
}
#pragma warning restore 414
