using System;
using System.Collections.Generic;
using UnityEngine.Scripting;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

[Preserve]
public partial class DB_FishRiver : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5307155828711052178UL,11210579068189473933UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String _name
	{
		get => __name[Index];
		set => __name[Index] = value;
	}
	public System.Int32 _Hp
	{
		get => __Hp[Index];
		set => __Hp.SetValue(this, value);
	}
	public System.Int32 _AbilityToAct
	{
		get => __AbilityToAct[Index];
		set => __AbilityToAct.SetValue(this, value);
	}
	public System.String _AbilityToAct_icon
	{
		get => __AbilityToAct_icon[Index];
		set => __AbilityToAct_icon[Index] = value;
	}
	public System.String _Skill_name
	{
		get => __Skill_name[Index];
		set => __Skill_name[Index] = value;
	}
	public System.Int32 _Damage
	{
		get => __Damage[Index];
		set => __Damage.SetValue(this, value);
	}
	public System.Int32 _Heal
	{
		get => __Heal[Index];
		set => __Heal.SetValue(this, value);
	}
	public System.Int32 _Support
	{
		get => __Support[Index];
		set => __Support.SetValue(this, value);
	}
	public System.String _Habitat
	{
		get => __Habitat[Index];
		set => __Habitat[Index] = value;
	}
	public System.Int32 _Probability
	{
		get => __Probability[Index];
		set => __Probability.SetValue(this, value);
	}
	public System.String _Description
	{
		get => __Description[Index];
		set => __Description[Index] = value;
	}
	public System.Single _Fish_length
	{
		get => __Fish_length[Index];
		set => __Fish_length.SetValue(this, value);
	}
	public System.Int32 _MaxStackSize
	{
		get => __MaxStackSize[Index];
		set => __MaxStackSize.SetValue(this, value);
	}
	public System.Single _Weight
	{
		get => __Weight[Index];
		set => __Weight.SetValue(this, value);
	}
	public System.Boolean _Check
	{
		get => __Check[Index];
		set => __Check.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77__name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __name => _ufle12jhs77__name ?? (_ufle12jhs77__name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5415392848779497364UL, 2559740640425672838UL), () => _ufle12jhs77__name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Hp;
	public static BansheeGz.BGDatabase.BGFieldInt __Hp => _ufle12jhs77__Hp ?? (_ufle12jhs77__Hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5403434908924482586UL, 1618225153200641182UL), () => _ufle12jhs77__Hp = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__AbilityToAct;
	public static BansheeGz.BGDatabase.BGFieldInt __AbilityToAct => _ufle12jhs77__AbilityToAct ?? (_ufle12jhs77__AbilityToAct = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4840671935118261721UL, 15418950457266718885UL), () => _ufle12jhs77__AbilityToAct = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__AbilityToAct_icon;
	public static BansheeGz.BGDatabase.BGFieldString __AbilityToAct_icon => _ufle12jhs77__AbilityToAct_icon ?? (_ufle12jhs77__AbilityToAct_icon = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4890664631387380985UL, 8030082837726385557UL), () => _ufle12jhs77__AbilityToAct_icon = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__Skill_name;
	public static BansheeGz.BGDatabase.BGFieldString __Skill_name => _ufle12jhs77__Skill_name ?? (_ufle12jhs77__Skill_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5400631693221497834UL, 3487511046303810455UL), () => _ufle12jhs77__Skill_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Damage;
	public static BansheeGz.BGDatabase.BGFieldInt __Damage => _ufle12jhs77__Damage ?? (_ufle12jhs77__Damage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4763915640078501843UL, 4362679078778737828UL), () => _ufle12jhs77__Damage = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Heal;
	public static BansheeGz.BGDatabase.BGFieldInt __Heal => _ufle12jhs77__Heal ?? (_ufle12jhs77__Heal = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5717107081168863611UL, 12688967423318131130UL), () => _ufle12jhs77__Heal = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Support;
	public static BansheeGz.BGDatabase.BGFieldInt __Support => _ufle12jhs77__Support ?? (_ufle12jhs77__Support = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4955468064340827489UL, 4818128033666500255UL), () => _ufle12jhs77__Support = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__Habitat;
	public static BansheeGz.BGDatabase.BGFieldString __Habitat => _ufle12jhs77__Habitat ?? (_ufle12jhs77__Habitat = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4706771234986255749UL, 1446375266631473081UL), () => _ufle12jhs77__Habitat = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Probability;
	public static BansheeGz.BGDatabase.BGFieldInt __Probability => _ufle12jhs77__Probability ?? (_ufle12jhs77__Probability = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4780960114952119424UL, 15036994820575784590UL), () => _ufle12jhs77__Probability = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__Description;
	public static BansheeGz.BGDatabase.BGFieldString __Description => _ufle12jhs77__Description ?? (_ufle12jhs77__Description = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5453964088521413050UL, 1279680616890487981UL), () => _ufle12jhs77__Description = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77__Fish_length;
	public static BansheeGz.BGDatabase.BGFieldFloat __Fish_length => _ufle12jhs77__Fish_length ?? (_ufle12jhs77__Fish_length = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5037568044438845758UL, 10381041534865328819UL), () => _ufle12jhs77__Fish_length = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__MaxStackSize;
	public static BansheeGz.BGDatabase.BGFieldInt __MaxStackSize => _ufle12jhs77__MaxStackSize ?? (_ufle12jhs77__MaxStackSize = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5583897987533328609UL, 8076968942157528504UL), () => _ufle12jhs77__MaxStackSize = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77__Weight;
	public static BansheeGz.BGDatabase.BGFieldFloat __Weight => _ufle12jhs77__Weight ?? (_ufle12jhs77__Weight = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(4690210422877305221UL, 3290983632278445503UL), () => _ufle12jhs77__Weight = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77__Check;
	public static BansheeGz.BGDatabase.BGFieldBool __Check => _ufle12jhs77__Check ?? (_ufle12jhs77__Check = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5083853200461738610UL, 8045118963229304763UL), () => _ufle12jhs77__Check = null));
	private DB_FishRiver() : base(MetaDefault) {}
	private DB_FishRiver(BGId id) : base(MetaDefault, id) {}
	private DB_FishRiver(BGMetaEntity meta) : base(meta) {}
	private DB_FishRiver(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_FishRiver FindEntity(Predicate<DB_FishRiver> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_FishRiver> FindEntities(Predicate<DB_FishRiver> filter, List<DB_FishRiver> result=null, Comparison<DB_FishRiver> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_FishRiver> action, Predicate<DB_FishRiver> filter=null, Comparison<DB_FishRiver> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_FishRiver GetEntity(BGId entityId) => (DB_FishRiver) MetaDefault.GetEntity(entityId);
	public static DB_FishRiver GetEntity(int index) => (DB_FishRiver) MetaDefault[index];
	public static DB_FishRiver GetEntity(string entityName) => (DB_FishRiver) MetaDefault.GetEntity(entityName);
	public static DB_FishRiver NewEntity() => (DB_FishRiver) MetaDefault.NewEntity();
	public static DB_FishRiver NewEntity(BGId entityId) => (DB_FishRiver) MetaDefault.NewEntity(entityId);
	public static DB_FishRiver NewEntity(Action<DB_FishRiver> callback) => (DB_FishRiver) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_FishRiver)entity)));

	[Preserve]
	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_FishRiver(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_FishRiver(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "FishRiver";
		public const string name = "name";
		public const string Hp = "Hp";
		public const string AbilityToAct = "AbilityToAct";
		public const string AbilityToAct_icon = "AbilityToAct_icon";
		public const string Skill_name = "Skill_name";
		public const string Damage = "Damage";
		public const string Heal = "Heal";
		public const string Support = "Support";
		public const string Habitat = "Habitat";
		public const string Probability = "Probability";
		public const string Description = "Description";
		public const string Fish_length = "Fish_length";
		public const string MaxStackSize = "MaxStackSize";
		public const string Weight = "Weight";
		public const string Check = "Check";
	}
}

[Preserve]
public partial class DB_FishOcean : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5640068678953238307UL,10303491490289556620UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String _name
	{
		get => __name[Index];
		set => __name[Index] = value;
	}
	public System.Int32 _Hp
	{
		get => __Hp[Index];
		set => __Hp.SetValue(this, value);
	}
	public System.Int32 _AbilityToAct
	{
		get => __AbilityToAct[Index];
		set => __AbilityToAct.SetValue(this, value);
	}
	public System.String _AbilityToAct_icon
	{
		get => __AbilityToAct_icon[Index];
		set => __AbilityToAct_icon[Index] = value;
	}
	public System.String _Skill_name
	{
		get => __Skill_name[Index];
		set => __Skill_name[Index] = value;
	}
	public System.Int32 _Damage
	{
		get => __Damage[Index];
		set => __Damage.SetValue(this, value);
	}
	public System.Int32 _Heal
	{
		get => __Heal[Index];
		set => __Heal.SetValue(this, value);
	}
	public System.Int32 _Support
	{
		get => __Support[Index];
		set => __Support.SetValue(this, value);
	}
	public System.String _Habitat
	{
		get => __Habitat[Index];
		set => __Habitat[Index] = value;
	}
	public System.Int32 _Probability
	{
		get => __Probability[Index];
		set => __Probability.SetValue(this, value);
	}
	public System.String _Description
	{
		get => __Description[Index];
		set => __Description[Index] = value;
	}
	public System.Single _Fish_length
	{
		get => __Fish_length[Index];
		set => __Fish_length.SetValue(this, value);
	}
	public System.Int32 _MaxStackSize
	{
		get => __MaxStackSize[Index];
		set => __MaxStackSize.SetValue(this, value);
	}
	public System.Single _Weight
	{
		get => __Weight[Index];
		set => __Weight.SetValue(this, value);
	}
	public System.Boolean _Check
	{
		get => __Check[Index];
		set => __Check.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77__name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __name => _ufle12jhs77__name ?? (_ufle12jhs77__name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5203231371621610676UL, 1611488776779468702UL), () => _ufle12jhs77__name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Hp;
	public static BansheeGz.BGDatabase.BGFieldInt __Hp => _ufle12jhs77__Hp ?? (_ufle12jhs77__Hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5174232290305173436UL, 8781243275405380012UL), () => _ufle12jhs77__Hp = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__AbilityToAct;
	public static BansheeGz.BGDatabase.BGFieldInt __AbilityToAct => _ufle12jhs77__AbilityToAct ?? (_ufle12jhs77__AbilityToAct = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5649281079788065407UL, 11146473597595040660UL), () => _ufle12jhs77__AbilityToAct = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__AbilityToAct_icon;
	public static BansheeGz.BGDatabase.BGFieldString __AbilityToAct_icon => _ufle12jhs77__AbilityToAct_icon ?? (_ufle12jhs77__AbilityToAct_icon = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5490623126734554464UL, 1786460506161355675UL), () => _ufle12jhs77__AbilityToAct_icon = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__Skill_name;
	public static BansheeGz.BGDatabase.BGFieldString __Skill_name => _ufle12jhs77__Skill_name ?? (_ufle12jhs77__Skill_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4931582514236600376UL, 11487933112305656496UL), () => _ufle12jhs77__Skill_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Damage;
	public static BansheeGz.BGDatabase.BGFieldInt __Damage => _ufle12jhs77__Damage ?? (_ufle12jhs77__Damage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5021764334931791088UL, 9232856134938593937UL), () => _ufle12jhs77__Damage = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Heal;
	public static BansheeGz.BGDatabase.BGFieldInt __Heal => _ufle12jhs77__Heal ?? (_ufle12jhs77__Heal = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5313162659324563983UL, 11283291948044818353UL), () => _ufle12jhs77__Heal = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Support;
	public static BansheeGz.BGDatabase.BGFieldInt __Support => _ufle12jhs77__Support ?? (_ufle12jhs77__Support = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4791112449711073990UL, 1522697784962837635UL), () => _ufle12jhs77__Support = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__Habitat;
	public static BansheeGz.BGDatabase.BGFieldString __Habitat => _ufle12jhs77__Habitat ?? (_ufle12jhs77__Habitat = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4654565597486598867UL, 6804213883635270036UL), () => _ufle12jhs77__Habitat = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Probability;
	public static BansheeGz.BGDatabase.BGFieldInt __Probability => _ufle12jhs77__Probability ?? (_ufle12jhs77__Probability = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5542925424727744446UL, 1935838597131035327UL), () => _ufle12jhs77__Probability = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__Description;
	public static BansheeGz.BGDatabase.BGFieldString __Description => _ufle12jhs77__Description ?? (_ufle12jhs77__Description = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4795895922861455503UL, 9757022360212192412UL), () => _ufle12jhs77__Description = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77__Fish_length;
	public static BansheeGz.BGDatabase.BGFieldFloat __Fish_length => _ufle12jhs77__Fish_length ?? (_ufle12jhs77__Fish_length = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5740234681256206584UL, 13802125812242256523UL), () => _ufle12jhs77__Fish_length = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__MaxStackSize;
	public static BansheeGz.BGDatabase.BGFieldInt __MaxStackSize => _ufle12jhs77__MaxStackSize ?? (_ufle12jhs77__MaxStackSize = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5410317259768974674UL, 6070994931239109292UL), () => _ufle12jhs77__MaxStackSize = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77__Weight;
	public static BansheeGz.BGDatabase.BGFieldFloat __Weight => _ufle12jhs77__Weight ?? (_ufle12jhs77__Weight = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5354675168134305164UL, 15169478222838396563UL), () => _ufle12jhs77__Weight = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77__Check;
	public static BansheeGz.BGDatabase.BGFieldBool __Check => _ufle12jhs77__Check ?? (_ufle12jhs77__Check = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(5743780943701751951UL, 16826233822115326893UL), () => _ufle12jhs77__Check = null));
	private DB_FishOcean() : base(MetaDefault) {}
	private DB_FishOcean(BGId id) : base(MetaDefault, id) {}
	private DB_FishOcean(BGMetaEntity meta) : base(meta) {}
	private DB_FishOcean(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_FishOcean FindEntity(Predicate<DB_FishOcean> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_FishOcean> FindEntities(Predicate<DB_FishOcean> filter, List<DB_FishOcean> result=null, Comparison<DB_FishOcean> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_FishOcean> action, Predicate<DB_FishOcean> filter=null, Comparison<DB_FishOcean> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_FishOcean GetEntity(BGId entityId) => (DB_FishOcean) MetaDefault.GetEntity(entityId);
	public static DB_FishOcean GetEntity(int index) => (DB_FishOcean) MetaDefault[index];
	public static DB_FishOcean GetEntity(string entityName) => (DB_FishOcean) MetaDefault.GetEntity(entityName);
	public static DB_FishOcean NewEntity() => (DB_FishOcean) MetaDefault.NewEntity();
	public static DB_FishOcean NewEntity(BGId entityId) => (DB_FishOcean) MetaDefault.NewEntity(entityId);
	public static DB_FishOcean NewEntity(Action<DB_FishOcean> callback) => (DB_FishOcean) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_FishOcean)entity)));

	[Preserve]
	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_FishOcean(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_FishOcean(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "FishOcean";
		public const string name = "name";
		public const string Hp = "Hp";
		public const string AbilityToAct = "AbilityToAct";
		public const string AbilityToAct_icon = "AbilityToAct_icon";
		public const string Skill_name = "Skill_name";
		public const string Damage = "Damage";
		public const string Heal = "Heal";
		public const string Support = "Support";
		public const string Habitat = "Habitat";
		public const string Probability = "Probability";
		public const string Description = "Description";
		public const string Fish_length = "Fish_length";
		public const string MaxStackSize = "MaxStackSize";
		public const string Weight = "Weight";
		public const string Check = "Check";
	}
}

[Preserve]
public partial class DB_FishLake : BGEntity
{
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5560984306225763593UL,9892102557027751583UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String _name
	{
		get => __name[Index];
		set => __name[Index] = value;
	}
	public System.Int32 _Hp
	{
		get => __Hp[Index];
		set => __Hp.SetValue(this, value);
	}
	public System.Int32 _AbilityToAct
	{
		get => __AbilityToAct[Index];
		set => __AbilityToAct.SetValue(this, value);
	}
	public System.String _AbilityToAct_icon
	{
		get => __AbilityToAct_icon[Index];
		set => __AbilityToAct_icon[Index] = value;
	}
	public System.String _Skill_name
	{
		get => __Skill_name[Index];
		set => __Skill_name[Index] = value;
	}
	public System.Int32 _Damage
	{
		get => __Damage[Index];
		set => __Damage.SetValue(this, value);
	}
	public System.Int32 _Heal
	{
		get => __Heal[Index];
		set => __Heal.SetValue(this, value);
	}
	public System.Int32 _Support
	{
		get => __Support[Index];
		set => __Support.SetValue(this, value);
	}
	public System.String _Habitat
	{
		get => __Habitat[Index];
		set => __Habitat[Index] = value;
	}
	public System.Int32 _Probability
	{
		get => __Probability[Index];
		set => __Probability.SetValue(this, value);
	}
	public System.String _Description
	{
		get => __Description[Index];
		set => __Description[Index] = value;
	}
	public System.Single _Fish_length
	{
		get => __Fish_length[Index];
		set => __Fish_length.SetValue(this, value);
	}
	public System.Int32 _MaxStackSize
	{
		get => __MaxStackSize[Index];
		set => __MaxStackSize.SetValue(this, value);
	}
	public System.Single _Weight
	{
		get => __Weight[Index];
		set => __Weight.SetValue(this, value);
	}
	public System.Boolean _Check
	{
		get => __Check[Index];
		set => __Check.SetValue(this, value);
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77__name;
	public static BansheeGz.BGDatabase.BGFieldEntityName __name => _ufle12jhs77__name ?? (_ufle12jhs77__name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5045520561611985804UL, 12371104935179130035UL), () => _ufle12jhs77__name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Hp;
	public static BansheeGz.BGDatabase.BGFieldInt __Hp => _ufle12jhs77__Hp ?? (_ufle12jhs77__Hp = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5704705637946529922UL, 7991778845071206046UL), () => _ufle12jhs77__Hp = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__AbilityToAct;
	public static BansheeGz.BGDatabase.BGFieldInt __AbilityToAct => _ufle12jhs77__AbilityToAct ?? (_ufle12jhs77__AbilityToAct = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5368075965366420038UL, 3628174215926008226UL), () => _ufle12jhs77__AbilityToAct = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__AbilityToAct_icon;
	public static BansheeGz.BGDatabase.BGFieldString __AbilityToAct_icon => _ufle12jhs77__AbilityToAct_icon ?? (_ufle12jhs77__AbilityToAct_icon = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5510431125834546457UL, 13703688639673701812UL), () => _ufle12jhs77__AbilityToAct_icon = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__Skill_name;
	public static BansheeGz.BGDatabase.BGFieldString __Skill_name => _ufle12jhs77__Skill_name ?? (_ufle12jhs77__Skill_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4687308779892288187UL, 11404193653849018288UL), () => _ufle12jhs77__Skill_name = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Damage;
	public static BansheeGz.BGDatabase.BGFieldInt __Damage => _ufle12jhs77__Damage ?? (_ufle12jhs77__Damage = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5751248046732169612UL, 2868805763113974935UL), () => _ufle12jhs77__Damage = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Heal;
	public static BansheeGz.BGDatabase.BGFieldInt __Heal => _ufle12jhs77__Heal ?? (_ufle12jhs77__Heal = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5454052037782380401UL, 14008414421192123017UL), () => _ufle12jhs77__Heal = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Support;
	public static BansheeGz.BGDatabase.BGFieldInt __Support => _ufle12jhs77__Support ?? (_ufle12jhs77__Support = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(4753544105094698958UL, 1311845227934253236UL), () => _ufle12jhs77__Support = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__Habitat;
	public static BansheeGz.BGDatabase.BGFieldString __Habitat => _ufle12jhs77__Habitat ?? (_ufle12jhs77__Habitat = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(5202296115580117291UL, 1388211540386024089UL), () => _ufle12jhs77__Habitat = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__Probability;
	public static BansheeGz.BGDatabase.BGFieldInt __Probability => _ufle12jhs77__Probability ?? (_ufle12jhs77__Probability = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5261378452605459351UL, 14491805233951288455UL), () => _ufle12jhs77__Probability = null));
	private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77__Description;
	public static BansheeGz.BGDatabase.BGFieldString __Description => _ufle12jhs77__Description ?? (_ufle12jhs77__Description = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldString>(MetaDefault, new BGId(4951050286627185142UL, 1447691313761944220UL), () => _ufle12jhs77__Description = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77__Fish_length;
	public static BansheeGz.BGDatabase.BGFieldFloat __Fish_length => _ufle12jhs77__Fish_length ?? (_ufle12jhs77__Fish_length = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5183735310652482815UL, 7439091674765211793UL), () => _ufle12jhs77__Fish_length = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77__MaxStackSize;
	public static BansheeGz.BGDatabase.BGFieldInt __MaxStackSize => _ufle12jhs77__MaxStackSize ?? (_ufle12jhs77__MaxStackSize = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5211317728524813621UL, 2693696612521573005UL), () => _ufle12jhs77__MaxStackSize = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77__Weight;
	public static BansheeGz.BGDatabase.BGFieldFloat __Weight => _ufle12jhs77__Weight ?? (_ufle12jhs77__Weight = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5024088679543999167UL, 11148223410802462848UL), () => _ufle12jhs77__Weight = null));
	private static BansheeGz.BGDatabase.BGFieldBool _ufle12jhs77__Check;
	public static BansheeGz.BGDatabase.BGFieldBool __Check => _ufle12jhs77__Check ?? (_ufle12jhs77__Check = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldBool>(MetaDefault, new BGId(4704219168888085743UL, 17113334918544427432UL), () => _ufle12jhs77__Check = null));
	private DB_FishLake() : base(MetaDefault) {}
	private DB_FishLake(BGId id) : base(MetaDefault, id) {}
	private DB_FishLake(BGMetaEntity meta) : base(meta) {}
	private DB_FishLake(BGMetaEntity meta, BGId id) : base(meta, id) {}
	public static DB_FishLake FindEntity(Predicate<DB_FishLake> filter) => BGCodeGenUtils.FindEntity(MetaDefault, filter);
	public static List<DB_FishLake> FindEntities(Predicate<DB_FishLake> filter, List<DB_FishLake> result=null, Comparison<DB_FishLake> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<DB_FishLake> action, Predicate<DB_FishLake> filter=null, Comparison<DB_FishLake> sort=null) => BGCodeGenUtils.ForEachEntity(MetaDefault, action, filter, sort);
	public static DB_FishLake GetEntity(BGId entityId) => (DB_FishLake) MetaDefault.GetEntity(entityId);
	public static DB_FishLake GetEntity(int index) => (DB_FishLake) MetaDefault[index];
	public static DB_FishLake GetEntity(string entityName) => (DB_FishLake) MetaDefault.GetEntity(entityName);
	public static DB_FishLake NewEntity() => (DB_FishLake) MetaDefault.NewEntity();
	public static DB_FishLake NewEntity(BGId entityId) => (DB_FishLake) MetaDefault.NewEntity(entityId);
	public static DB_FishLake NewEntity(Action<DB_FishLake> callback) => (DB_FishLake) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((DB_FishLake)entity)));

	[Preserve]
	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new DB_FishLake(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new DB_FishLake(meta, id);
	}

	public static class __Names
	{
		public const string Meta = "FishLake";
		public const string name = "name";
		public const string Hp = "Hp";
		public const string AbilityToAct = "AbilityToAct";
		public const string AbilityToAct_icon = "AbilityToAct_icon";
		public const string Skill_name = "Skill_name";
		public const string Damage = "Damage";
		public const string Heal = "Heal";
		public const string Support = "Support";
		public const string Habitat = "Habitat";
		public const string Probability = "Probability";
		public const string Description = "Description";
		public const string Fish_length = "Fish_length";
		public const string MaxStackSize = "MaxStackSize";
		public const string Weight = "Weight";
		public const string Check = "Check";
	}
}
#pragma warning restore 414
